---
- name: Ensure Eiffel Demo OpenStack nova flavors exist
  hosts: localhost
  tags:
    - flavors
  roles:
    - role: stackhpc.os-flavors
      os_flavors_venv: "{{ eiffel_venv }}"
      os_flavors_auth_type: "{{ openstack_auth_type }}"
      os_flavors_auth: "{{ openstack_auth }}"
      os_flavors_cacert: "{{ openstack_cacert }}"
      os_flavors: "{{ eiffel_flavors }}"
