---
- name: Ensure Eiffel Demo OpenStack networks exist
  hosts: localhost
  tags:
    - networks
  roles:
    - role: stackhpc.os-networks
      os_networks_venv: "{{ eiffel_venv }}"
      os_networks_auth_type: "{{ openstack_auth_type }}"
      os_networks_auth: "{{ openstack_auth }}"
      os_networks_cacert: "{{ openstack_cacert }}"
      os_networks: "{{ eiffel_networks }}"
      os_networks_routers: "{{ eiffel_routers }}"
      os_networks_security_groups: "{{ eiffel_security_groups }}"
