---
- name: Ensure Eiffel POC container clusters exist
  hosts: localhost
  tags:
    - container-clusters
  roles:
    - role: stackhpc.os-container-clusters
      os_container_clusters_venv: "{{ eiffel_venv }}"
      os_container_clusters_auth_type: "{{ openstack_auth_type }}"
      os_container_clusters_auth: "{{ openstack_auth }}"
      os_container_clusters_templates: "{{ eiffel_container_clusters_templates }}"

